SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8 # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_COOLDOWN = 0.3  # seconds
PLAYER_SHOOT_SPEED = 500

SHOT_RADIUS = 5

# Gold orb constants
GOLD_ORB_RADIUS = 8
GOLD_ORB_COLLECTION_DISTANCE = 30
POINTS_PER_ORB = 100

# High score constants
HIGH_SCORE_FILE = "high_scores.txt"
MAX_NAME_LENGTH = 15
TOP_SCORES_COUNT = 3

# Countdown constants
COUNTDOWN_DURATION = 3.0  # seconds
PREPARE_DISPLAY_TIME = 1.5  # seconds

# Meteorite and star constants
METEORITE_RADIUS = 15
METEORITE_SPEED = 400
METEORITE_SPAWN_RATE = 8.0  # seconds
STAR_RADIUS = 12
STAR_BLINK_RATE = 0.3  # seconds
STAR_COLLECTION_DISTANCE = 35
STAR_EXPLOSION_RADIUS = 1000  # Large enough to cover entire screen
STAR_EXPLOSION_DURATION = 0.5  # seconds
STAR_WHITE_FLASH_DURATION = 1.0  # seconds
